{{- if .Values.configuration.env.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3-explorer.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.configuration.env.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}
{{- end}}