# Default values for s3-explorer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: s3-explorer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configuration:
  args:
    - "--bucket=some-bucket"
    - "--max_files=500"
  env:
    normal:
      AWS_DEFAULT_REGION: us-east-1


podAnnotations: {}
service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: s3-explorer.local
      paths:
        - "/"
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - s3-explorer.local

resources: 
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

livenessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 15
readinessProbe:
  initialDelaySeconds: 5
  timeoutSeconds: 2
  periodSeconds: 15


