on:
  push:
    branches:
      - master
name: master-build
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.17.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint s3_explorer/deploy/helm/s3-explorer/

      - name: Install helm s3 plugin
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm plugin install https://github.com/hypnoglow/helm-s3.git

      - name: Helm package
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm package s3_explorer/deploy/helm/s3-explorer/

      - name: Docker build 
        run: docker build -t s3-explorer -f s3_explorer/Dockerfile s3_explorer/
      

      - name: Configure AWS credentials dev account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Helm add-repo
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm repo add s3://helm-tests/charts s3-repo

      - name: Helm package
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm s3 push s3_explorer/deploy/helm/s3-explorer-*.tgz  s3-repo

